# Generated by Django 4.2.13 on 2024-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(unique=True, verbose_name="URL")),
                ("short_url", models.CharField(max_length=20)),
            ],
        ),
    ]
